plugins {
    id 'java'
    id 'java-library'
}

group = project.findProperty('group') ?: 'com.github.nastarozina'
version = project.findProperty('version') ?: '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.springframework.boot:spring-boot-starter:4.1.1"
    implementation 'org.springframework.boot:spring-boot-starter-webmvc:4.1.1'

    compileOnly 'org.projectlombok:lombok:1.18.42'
    annotationProcessor 'org.projectlombok:lombok:1.18.42'
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(25))
    }
}